### ISSUE TITLE
Can I deploy to vercel?

### ISSUE THREAD

**Issue by MYSTERYS-ARE-FUN** [KlausJackson/Chat-Room#2]
Sorry I didn’t know what to choose so I just chose future request but if it’s not a feature pls make it one

**Comment by KlausJackson** [comment]
Yes, you're free to use my code however you want.

**Comment by MYSTERYS-ARE-FUN** [comment]
Like make a button that says deploy to vercel I don’t know if you need like a special something but some people have like a deploy to vercel and deploy to heroku and type of stuff, if you need a screen shot I can upload one as an example

**Comment by KlausJackson** [comment]
Ok, I understand your point now. I just did a little research, I know I will have to go through quite a trouble to make that, I'm very sorry to say no to your request.

You can deploy the server manually or make that feature, test if it works then contribute to this project since I'm not available to code the feature myself. 

I recommend add a new code file (`deploy_vercel.py``) outside both versions, if the user wants to deploy then they will run that script along with the path to server.py that they choose to deploy. 
For example: deploy_vercel.py "path_to_server.py"

It's been nice to chat with you. Close the issue if that's all.

**Comment by MYSTERYS-ARE-FUN** [comment]
Ok I’ll see, if you want to ask me if I’m done with it my discord is @qwertyhigkl
